#include "disk.h"

/**
 * Disk_error
 * 
 * @brief Disk error log printer
 * @details This function prints the name of the current disk loaded
 * and the error generated by the called function
 * 
 * @param disk Current disk loaded that caused the error
 * @param msg Error msg
 * @return
*/
void Disk_error(Disk *disk, char *msg) {
    printf("[%s] %s\n", disk->name, strerror(errno));
    return;
}


Disk* Disk_create(char *name) {
    Disk *disk = malloc(sizeof(Disk));
    strcpy(disk->name, name);
    disk->fd = -1;
    return disk;
}

int Disk_destroy(Disk *disk) {
    if (disk) free(disk);
    return DISK_OK;
}

int Disk_open(Disk *disk) {
    int fd;

    fd = open(disk->name, O_CREAT | O_RDWR, 0666);

    if (fd == -1) {
        Disk_error(disk, "Unable to open the file");
        return DISK_ERROR;
    }

    disk->fd = fd;
    return DISK_OK;
}

int Disk_close(Disk *disk) {
    if (disk && disk->fd != -1) close(disk->fd);
    return DISK_OK;
}

int Disk_write(Disk *disk, char *buf, int size){
    write(disk->fd, buf, size);
    return DISK_OK;
}

int Disk_read(Disk *disk, char *buf, int size) {
    read(disk->fd, buf, size);
    return DISK_OK;
}
